# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('email', models.EmailField(max_length=254)),
                ('message_text', models.CharField(max_length=2000)),
            ],
        ),
    ]
